### ISSUE TITLE
Safari Technology Preview 46 enables Service Workers by default

### ISSUE THREAD

**Issue by Schweinepriester** [jakearchibald/isserviceworkerready#102]
Per <https://webkit.org/blog/8042/release-notes-for-safari-technology-preview-46/>:

> Made Service Workers enabled by default

🎉

Looking at that changelog for Service Workers alone and previous ones, I suspect several features need to become green? 0:-)

**Comment by jfbrennan** [comment]
Safari 11.1 ships with it: https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html#//apple_ref/doc/uid/TP40014305-CH14-SW2

**Comment by laistomazz** [comment]
> iOS 11.3 and macOS 10.13.4 include Service Workers — a powerful specification that allows background scripts to power offline web applications. iOS 11.3 also consults Web App Manifest when adding web apps to the home screen.

https://twitter.com/rmondello/status/956256845311590400

**Comment by dafzthomas** [comment]
@laistomazz Does this mean that Safari on iOS has the same service worker implementation? Meaning offline websites on iOS?

**Comment by laistomazz** [comment]
@dafzthomas We're still lacking official documentation, but it seems like it's all there to make the website work offline.
Unfortunately, they didn't implement the Push API, so no push notifications for us. Frustrating.

**Comment by js-choi** [comment]
Youenn Fablet of WebKit has published a [blog post regarding WebKit’s policies on service workers](https://webkit.org/blog/8090/workers-at-your-service/).

**Comment by Schweinepriester** [comment]
As https://jakearchibald.github.io/isserviceworkerready/ has been updated long ago, I think this issue can be closed 😅
