### ISSUE TITLE
iOS 12.2 safari does not support service worker

### ISSUE THREAD

**Issue by lili21** [jakearchibald/isserviceworkerready#110]
![image](https://user-images.githubusercontent.com/4456380/55859090-e3bb2380-5ba3-11e9-9ca4-7c9dccf500c5.png)

**Comment by chetanraj** [comment]
@lili21 - Were you able to solve this issue ?

**Comment by lili21** [comment]
You need to use https.

**Comment by chetanraj** [comment]
@lili21 - I'm using https, still the issue persists.

**Comment by lili21** [comment]
safari or wkwebview ? the webview doesn't support it yet.

**Comment by chetanraj** [comment]
It's safari, Hybrid App to be precise..
