### ISSUE TITLE
postMessage to & from worker fails in Chrome 41

### ISSUE THREAD

**Issue by dstockwell** [jakearchibald/isserviceworkerready#30]
https://jakearchibald.github.io/isserviceworkerready/demos/postMessage/

    Error, TypeError: undefined is not a function

Here: https://github.com/jakearchibald/isserviceworkerready/blob/f0c3e98fc3662cfa376e827fd263f12241d60cbe/src/demos/postMessage/index.html#L38

**Comment by jakearchibald** [comment]
Thanks for spotting this!
