### ISSUE TITLE
Samsung Browser

### ISSUE THREAD

**Issue by torgo** [jakearchibald/isserviceworkerready#63]
As you're explicitly calling out (Chromium-based) Opera, can you also explicitly add (Chromium-based) Samsung Browser to your list? Samsung browser has pretty significant market share among mobile browsers, see http://gs.statcounter.com/#mobile_browser-eu-monthly-201504-201604 and is definitely shipping Service Workers, see http://developer.samsung.com/technical-doc/view.do?v=T000000245L.

**Comment by jakearchibald** [comment]
Sure, happy to accept a pull request!

**Comment by jungkees** [comment]
@jakearchibald I made a PR: https://github.com/jakearchibald/isserviceworkerready/pull/71 :-)

**Comment by alrra** [comment]
@jakearchibald This issue can be closed since #71 was merged.

**Comment by jakearchibald** [comment]
Ahh yes, cheers!
